version: '2'

services:

### Application Code Container #############################
    application:
        image: tianon/true
        volumes:
            - ../:/var/www

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - TZ=UTC
        volumes_from:
              - application
        extra_hosts:
        # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
              - "dockerhost:10.0.75.1"

### PHP-FPM Container #######################################
    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile
        volumes_from:
                - application
        expose:
            - "9000"
        extra_hosts:
            - "dockerhost:10.0.75.1"
        tty: true

### Nginx Server Container ##################################
    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - application
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: nextup
            POSTGRES_USER: homestead
            POSTGRES_PASSWORD: secret

### Volumes Setup ###########################################
volumes:
    postgres:
        driver: "local"